/**
 * GET /api/models/[modelId]/versions/[versionId]/license.txt  (keystone §7)
 *
 * Virtual LICENSE.txt, server-rendered from the license FROZEN to this version
 * at publish (no file mutation — license is delivered as metadata). Public for a
 * published version of a published model; owner/admin may also view it for an
 * unpublished one. The download modal and license badges read the same frozen
 * code.
 */
import { extractAccessToken } from '../../../../../utils/userAuth';
import { isAdminAuthenticated } from '../../../../../utils/adminAuth';
import { getServiceClient } from '../../../../../utils/supabase';

export default defineEventHandler(async (event) => {
  const modelId = getRouterParam(event, 'modelId');
  const versionId = getRouterParam(event, 'versionId');
  if (!modelId || !versionId) {
    throw createError({ statusCode: 400, statusMessage: 'Missing model or version id' });
  }

  const service = getServiceClient();

  const { data: version, error: versionError } = await service
    .from('model_versions')
    .select('id, model_id, license_code, status')
    .eq('id', versionId)
    .single();

  if (versionError || !version || version.model_id !== modelId) {
    throw createError({ statusCode: 404, statusMessage: 'Version not found' });
  }

  const { data: model, error: modelError } = await service
    .from('models')
    .select('owner_id, status, title, slug, license_code')
    .eq('id', modelId)
    .single();

  if (modelError || !model) {
    throw createError({ statusCode: 404, statusMessage: 'Model not found' });
  }

  const isPublic = version.status === 'published' && model.status === 'published';
  if (!isPublic && !(await canViewUnpublished(event, model.owner_id))) {
    throw createError({ statusCode: 404, statusMessage: 'Version not found' });
  }

  // Prefer the version's frozen license; fall back to the model's current
  // selection for drafts that have not been published yet.
  const code = version.license_code ?? model.license_code;
  const { data: license, error: licenseError } = await service
    .from('model_licenses')
    .select('code, name, url, license_text')
    .eq('code', code)
    .single();

  if (licenseError || !license) {
    throw createError({ statusCode: 500, statusMessage: 'License not found' });
  }

  const config = useRuntimeConfig();
  const siteUrl = ((config.public.siteUrl as string) || 'https://www.classicminidiy.com').replace(/\/$/, '');
  const text = renderLicense({
    title: model.title,
    modelUrl: `${siteUrl}/models/${model.slug}`,
    licenseName: license.name,
    licenseCode: license.code,
    licenseUrl: license.url,
    licenseText: license.license_text,
  });

  setHeader(event, 'content-type', 'text/plain; charset=utf-8');
  setHeader(event, 'content-disposition', 'inline; filename="LICENSE.txt"');
  setHeader(event, 'cache-control', 'no-store');
  return text;
});

/** Owner or admin may view the license for an unpublished version. */
async function canViewUnpublished(event: any, ownerId: string): Promise<boolean> {
  const token = extractAccessToken(event);
  if (token) {
    const { data } = await getServiceClient().auth.getUser(token);
    if (data?.user?.id === ownerId) return true;
  }
  return isAdminAuthenticated(event);
}

function renderLicense(opts: {
  title: string;
  modelUrl: string;
  licenseName: string;
  licenseCode: string;
  licenseUrl: string | null;
  licenseText: string | null;
}): string {
  const divider = '-'.repeat(70);
  const lines = [
    'CLASSIC MINI DIY — 3D MODEL LICENSE',
    '',
    `Model:    ${opts.title}`,
    `URL:      ${opts.modelUrl}`,
    `License:  ${opts.licenseName} (${opts.licenseCode})`,
  ];
  if (opts.licenseUrl) lines.push(`Reference: ${opts.licenseUrl}`);
  lines.push('', divider, '');
  lines.push(opts.licenseText?.trim() || '(See the reference URL above for the full license text.)');
  lines.push(
    '',
    divider,
    '',
    'This license file was generated by classicminidiy.com and reflects the',
    'license frozen to this version of the model at publish time.'
  );
  return lines.join('\n') + '\n';
}
